# Ejercicio 1: Variables y Tipos de Datos en Python
# Objetivo: Entender cómo se declaran las variables y los tipos de datos en Python.
#Una variable es un espacio en la memoria del ordenador donde se almacena un valor, es como una "caja" que guarda información para que puedas usarla más adelante en tu programa.

#Declaramos Las variables
nombre = "Montse" # Cadena de texto
edad = 51  # Entero
altura = 1.73  # Float

#Imprimimos los valores de las variables en pantalla:
print("Nombre:", nombre)
print("Edad:", edad, "años")
print("Altura:", altura, "metros")

#Guardar el archivo y ejecutar el código haciendo clic en el botón de "PLAY".
#En la consola, verás que se imprimen los valores de las variables que declaramos.
#En este caso, el nombre, la edad y la altura de una persona.
#Ahora, vamos a declarar una variable de tipo booleano. 
#Un valor booleano es un tipo de dato que puede ser verdadero o falso.

#Declaramos la variable:    
es_mayor_de_edad = True  # Booleanoif edad >= 18:
#Si la edad es mayor o igual a 18, la variable es_mayor_de_edad será True.
#Si la edad es menor a 18, la variable es_mayor_de_edad será False.
#Imprimimos el valor de la variable en pantalla:    
print("¿Es mayor de edad?", "Sí" if es_mayor_de_edad else "No")
#Utilizo las funciones condicionales is y else, para traducir el valor booleano (True/False) a español (Sí/No).

#Guardar el archivo y ejecutar el código haciendo clic en el botón de "PLAY".
